#' Calculate the growth suppression index
#'
#' This function removes the nonhost growth signal from a host tree-ring series.
#'
#' @details The growth suppression index (GSI) is referred to as the "corrected"
#'   series in OUTBREAK. It is calculated as:
#'
#'   \deqn{GSI(i) = H(i) - (NH(i) - mean(NH)) sd(H)/sd(NH)}
#'
#'   where H and NH are the host and nonhost tree-ring series as standardized
#'   index values; i is the year, and the functions \code{mean} and \code{sd}
#'   are applied to the common period.
#'
#'   \code{gsi} will rarely be run directly by a user. It is called from
#'   \code{defoliate_trees}.
#'
#' @param input_series data frame rwl object with the host tree series as the
#'   first column and the non-host chronology as the second. Years should be
#'   \code{row.names}.
#'
#' @return data frame with the two input columns (host and nonhost series) and 3
#'   added columns:
#'
#'   \enumerate{
#'   \item The mean/sd adjusted non-host chronology,
#'   \item The growth suppression index (gsi) of the host series after subtraction of the
#'   adjusted nonhost chronology,
#'   \item The normalized growth suppression index
#'   (ngsi) generated by applying \code{scale} to the gsi.
#'   }
#'
#' @export
gsi <- function(input_series){
  nms <- colnames(input_series)
  nam1 <- paste(nms[2], '_rescale', sep='')
  nam2 <- paste(nms[1], '_gsi', sep='')
  nam3 <- paste(nms[1], '_ngsi', sep='')
  h_sd <- stats::sd(input_series[, 1])
  nh_sd <- stats::sd(input_series[, 2])
  nh_mean <- mean(input_series[, 2])
  # To Do: Add provision to prevent large non-host values from swaying results
  # See outbreak.txt for description of fractional power.
  input_series[, 3] <- (input_series[, 2] - nh_mean) * (h_sd / nh_sd)
  input_series[, 4] <- input_series[, 1] - input_series[, 3]
  # input_series[, 4] <- replace(input_series[, 4], input_series[, 4] < 0, 0) # set negative #s to zero
  input_series[, 5] <- as.numeric(scale(input_series[, 4]))
  names(input_series) <- c(nms, nam1, nam2, nam3)
  return(input_series)
}

#' Identify defoliation events in a host series
#'
#' @param input_series a data frame with 5 columns, as generated by \code{gsi}.
#'
#' @param duration_years the minimum length of time in which the tree is
#'   considered to be in defoliation
#'
#' @param max_reduction minimum value of ngsi required to be considered a defoliation
#'   event. If a sequence of negative ngsi values does not reach this threshold,
#'   the potential event is rejected. Defaults to -1.28
#'
#' @param bridge_events Binary, defaults to \code{FALSE}. This option allows for
#'   successive events that are separated by a single year to be bridged and become one
#'   event. It should be used cautiously and closely evaluated to ensure the
#'   likelihood that the two (or more) events are actually one long event.
#'
#' @param series_end_event Binary, defaults to \code{FALSE}. This option allows
#'   the user to identify an event ocuring at the time of sampling as a
#'   defoliation event, regardless of duration. Including it will help to
#'   quantify periodicity and extent of an outbreak. This should only be used if
#'   the user has direct knowledge of an ongoing defoliation event when the
#'   trees were sampled.
#'
#' @return after performing runs analyses, the function adds a column to the
#'   input data frame that distinguishes years of defoliation and the maximum
#'   defoliation year (ie. the year the greatest negative growth departure
#'   within the event).
#'
#' @export
id_defoliation <- function(input_series, duration_years = 8, max_reduction = -1.28, bridge_events = FALSE, series_end_event = FALSE){
  rns <- rle(as.vector(input_series[, 5] < 0))
  rns.index = cumsum(rns$lengths)
  neg.runs.pos <- which(rns$values == TRUE)
  ends <- rns.index[neg.runs.pos]
  newindex = ifelse(neg.runs.pos > 1, neg.runs.pos - 1, 0)
  starts <- rns.index[newindex] + 1
  if (0 %in% newindex) starts = c(1,starts)
  deps <- data.frame(cbind(starts, ends))
  deps$length <- deps$ends - deps$starts + 1
  input_series$defol_status = NA
  for(y in 1:nrow(deps)){
    if(any(input_series[deps$starts[y] : deps$ends[y], ]$defol_status %in% c("defoliated", "max_defoliation"))) next
    bb <- input_series[deps$starts[y] : deps$ends[y], 5]
    max.red <- deps$starts[y] + which.min(bb) - 1
    if(input_series[max.red, 5] > max_reduction) next  # Includes setting for max growth reduction
    dep.seq <- deps$starts[y] : deps$ends[y]
    prev.flag <- FALSE
    if(y > 1){
      if(min(dep.seq) - deps$ends[y - 1] == 2) {
        if(! any(input_series[deps$starts[y - 1] : deps$ends[y - 1], ]$defol_status  %in% c("defoliated", "max_defoliation"))){
          dep.seq <- c(deps$starts[y - 1] : max(dep.seq))
          prev.flag <- TRUE
        }
      }
    }
    if(y < nrow(deps)){
      if(deps$starts[y + 1] - max(dep.seq) == 2){
        if(min(input_series[dep.seq, 5]) > min(input_series[deps$starts[y + 1] : deps$ends[y + 1], 5]))  next
        if((! prev.flag) & (y < nrow(deps) - 1)){
          if(deps$starts[y + 2] - deps$ends[y + 1] == 2){
            if(min(input_series[dep.seq, 5]) > min(input_series[deps$starts[y + 2] : deps$ends[y + 2], 5]))  next
          }
        }
        dep.seq <- c(min(dep.seq) : deps$ends[y + 1])
      }
    }
    if(series_end_event){
      if(any((deps[y, 'ends'] - nrow(input_series)) == c(0:2))){
        dep.seq <- c(min(dep.seq) : nrow(input_series))
      }
    }
    if(!(y == nrow(deps) & series_end_event)){
      if(length(dep.seq) < duration_years) next # Includes setting for min defoliation duration
    }
    input_series[dep.seq, "defol_status"] <- "defoliated"
    input_series[max.red, "defol_status"] <- "max_defoliation"
    if(y > 1 & bridge_events){
      if(any(input_series[min(dep.seq) - 2, ]$defol_status %in% c("defoliated", "max_defoliation"))){
        input_series[min(dep.seq) - 1, "defol_status"] <- "defoliated"
      }
    }
  }
  return(input_series)
}


#' Stack a defoliation list
#'
#' @param x a list object created by \code{defoliate_trees}
#'
#' @return a defol object (long-format data frame)
#' @export
stack_defoliation <- function(x){
  out <- plyr::ldply(x, function(i){
    inout <- range(as.numeric(rownames(i)))
    yrs <- as.integer(c(inout[1]:inout[2]))
    out <- data.frame(year = yrs, series = colnames(i)[1],
                      gsi = i[, 4],
                      ngsi = i[, 5],
                      defol_status = i[, 6])
    return(out)
    }
  )
  class(out) <- c('defol', 'data.frame')
  return(out)
}

#' Check if object is defol, indicating tree-level defoliation object
#'
#' @param x Any R object.
#'
#' @return Boolean indicating whether `x` is a defol object.
#'
#' @export
is.defol <- function(x) {
  inherits(x, 'defol')
}

#' Check if object is outbreak, meaning site-level outbreak object
#'
#' @param x Any R object.
#'
#' @return Boolean indicating whether `x` is an outbreak object.
#'
#' @export
is.outbreak <- function(x) {
  inherits(x, 'outbreak')
}


